### ISSUE TITLE
cannot load such file -- roadie/rails

### ISSUE THREAD

**Issue by hallmatt** [Mange/roadie-rails#39]
I'm on Rails 4.1.8 and Ruby 2.0.0 and am getting this error after bundling:

cannot load such file -- roadie/rails

Perhaps I'm missing a config file, but could be a bug.

**Comment by Mange** [comment]
Where are you getting this? While booting up your app? Can you get a stack trace and see the line that causes the require to happen?

**Comment by hallmatt** [comment]
I received the Roadie upgrade message about moving from 2.x to 3.x and then I received the error. I tried upgrading the gem, and I also tried removing/re-adding the gem without any luck. Here's the full error:

```
/Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- roadie/rails (LoadError)
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/roadie-3.0.4/lib/roadie/upgrade_guide.rb:9:in `<top (required)>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/roadie-3.0.4/lib/roadie.rb:26:in `<top (required)>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `each'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `block in require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `each'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `require'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.8.5/lib/bundler.rb:134:in `require'
  from /Users/useraccount/Rails/shed-configurator/config/application.rb:7:in `<top (required)>'
  from /Users/useraccount/Rails/shed-configurator/config/environment.rb:2:in `require'
  from /Users/useraccount/Rails/shed-configurator/config/environment.rb:2:in `<top (required)>'
  from config.ru:4:in `require'
  from config.ru:4:in `block in <main>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from config.ru:1:in `new'
  from config.ru:1:in `<main>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `call'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `block in rails_builder'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `call'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:628:in `init_worker_process'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:651:in `worker_loop'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/bin/unicorn_rails:23:in `load'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/bin/unicorn_rails:23:in `<main>'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
  from /Users/useraccount/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Mange** [comment]
Oh, yeah. You need to specify `ROADIE_I_KNOW_ABOUT_VERSION_3` somewhere before `roadie` is included, as the warning tells you.

This happens because you have the constant `Rails` defined, but no `roadie-rails` gem present. What's your setup?

**Comment by Mange** [comment]
Closing until I get some more details. Feel free to re-open if this happens to you!
